flop: /Users/jeremy/Documents/asapp/flop2
distiller: /Users/jeremy/Documents/asapp/distiller

---

!Experiment

name: jeremy-enwiki-l1

resources:
  data_file: /Users/jeremy/Downloads/enwik8
  # checkpoint: /Users/jeremy/Downloads/enwik8_sru_6_3056_512_lr2_wm16k.30.pt

pipeline:

  prune_normal: !Script
    script: flop.scripts.enwik8.train_enwik8_agp_struct
    args: []
    kwargs:
      warmup_steps: 4000
      prune_sparsity: 0
      l1_lambda: 0
      data: !@ data_file
      prune: 0
      # load: !@ checkpoint

  prune_large: !Script
    script: flop.scripts.enwik8.train_enwik8_agp_struct
    args: []
    kwargs:
      warmup_steps: 4000
      prune_end_epoch: !g [1, 5]
      prune_sparsity: 0.8
      l1_lambda: 0
      data: !@ data_file
      # load: !@ checkpoint
